language: java

jdk: oraclejdk7

env:
  matrix:
      - ANDROID_SDKS=android-18,sysimg-18  ANDROID_TARGET=android-18  ANDROID_ABI=armeabi-v7a
  global:
      - secure: "dlybePpaOj7Hfa1STpzM/qhTe3yWKYoF30p+F3SdHSN5ke7158Xu+BXb9IxEEMgP1UKzOFUPWgmbxcYfMUw7uKKhmc2OrRjHfdVCOUzJZhbbqGaAceZWE/F7b/53NDql7LRF6jDHxsoUoTIQWuFjTJ6dUa5k5dQXE0fKYAp/DUE="
      - secure: "CVyo7x5rlSrwQgUiw5y1W8QwqmnOJ2If0Wq8t1kkJY2iLCRcj5lvqVeBGnpnhKZ8a1D8Wqf4BXXsMzg3q55D0G67z/Y7Ewg4L6+V3xO0Pv+KaFCdw3GStMp8yOzz1oby6L2EwGlGOays9lokCmZeNZoiA0Q3/qlpcK+rLU/hG6Y="
      - secure: "H7PxEjbwZZLOLpoKgqNkQqHDn4AYMEy2XyyovOKtU67gGC5KaP798Cs8CoIydOZOy19Z6h6om6yJzPLUMtQ5IKeBzyasCeG52TBVijB/BeP1uOCIuzCbELeYmZQFmHsTUZOXFj/YFTDLMb9P0t8qQB+8ygk7qvycai+etAZddmQ="
      - secure: "OnWDITQVeHh556nUh1svw52kJva//nD2vVAg4sMejkAOfMSeNajdPhc0ePE1U99bH/ZOamuWeIu77eDbW2K3Hikd8SZFr/x0byoM/VlFsqNAlRrn9Ju9MyD4Vns8E2XFelo+xqtJbeIvRBK4xR4QcmVFXxyz6/tpke/OkKEP8lo="
      - secure: "XpPRkUZbj7a+NKpuNuTILXtoaQADgxVKuHU0wSKEr2iLTw3MjOoYwp8YHzFcfUG2x5aRUW/HbRo6ZKSxJ2TcEN0idWwXwYNcsReD/t6OfogMQKZJutbrhxtUyFO5FPMmCk75VEIPdVjzqR0JV8NuTz/wIGcOP3w2rWpSEk+26dE="
  
before_install:
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm
      ia32-libs ia32-libs-multiarch; fi
    - wget http://dl.google.com/android/android-sdk_r22-linux.tgz
    - tar xzf android-sdk_r22-linux.tgz
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    - echo yes | android update sdk --filter platform-tools --no-ui --force
    - echo yes | android update sdk --filter build-tools-18.1.1 --no-ui --force
    - echo yes | android update sdk --filter android-18 --no-ui --force
    - echo yes | android update sdk --filter sysimg-18 --no-ui --force
    - echo yes | android update sdk --filter extra-android-support --no-ui --force
    - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force
    - wget https://raw.github.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh -O dropbox_uploader.sh
script:
    - ./gradlew build
    
after_success:
    - touch dropbox_conf_empty.conf
    - bash dropbox_uploader.sh -f ./dropbox_conf_empty.conf upload Feedo/build/apk/Feedo-release-unsigned.apk FeedoNightly.apk 
    - bash dropbox_uploader.sh -f ./dropbox_conf_empty.conf share FeedoNightly.apk 
