language: java

jdk: oraclejdk7

env:
  matrix:
  - ANDROID_SDKS=android-18,sysimg-18  ANDROID_TARGET=android-18  ANDROID_ABI=armeabi-v7a
  global:
  - secure: CKBn85dzZp7aUC4veGzvZrviZJA/y47nIiwHYi69MMqlDqAcL0szQue0w5250DNx1GHq+ZozzjJRTn71V0AgpytC6sQ5fpyufJbfy3jiMO1uRYOzu4iTijvSXJJQ+Pyn52/8o7B+YuaEHHYGyIU5NTlymsLysFGarT8cmeVpWD8=
  - secure: Z9st7zY5GUdgVgBjaA2nn2D6cW/Yo8XRbSKjuNHnN0mPtIw5ALZq3b0fS87HK0DleAcOdZX5GuH9kx455CwuWL4a5UGTuoA134DRDMR7Dc4c9SNsz8P+V2nXZLMQSQWOSPY38d6yALcmK2xVU1xeAwJIK7ZPpqC7XjHcjAe3X0U=
  - secure: P5oyy9JSNkfs0bGmZ4zBnvl2B4fzXDePX5c1T1toDHEiSZfCcf+aqFcxzrOzGtYs5CzlOVpEvVn5A/XVjZHkG9COtz1kRvHZ2UxGYf0hRgH5dhERQ/A6rYRtAZuobw6ycNH/IBcRgcuNrJJufA3w/OipfxPiNb4jrnR9DTpWiFc=
  - secure: nIsALk2RszAd5vOdGLfd4Eugb/iYUtITOOrccQlM4r0aUfZUa4DIaqGAD9I9Fq0LhnTFMa3V/5nHSqhfcqrWlaV0o3x/L9h5DaUxSzKaZ0bnjqCmjAKwaN441tAVzfAZ0AblpYSjr6zS8HdlkJVF2Rcd1R7GbKLS8r3vvYPcYrs=
  - secure: LvftlGN0dzp75VpIu8QBbdUTQuAd7dqaTEXCWP2w/gY3BD7rhqZDk50SGOwxp8onAj7zpRP6Ltjh/YL6jlxMqggwwPHDY8peTCYQ1qHIQt+KTOTkWmvXo0cbw+m6a6hhGtEsPZ8/KtOjnbQOPX/CSjTkDiK7h2IWPaqffWY4H6Q=
  
before_install:
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm
      ia32-libs ia32-libs-multiarch; fi
    - wget http://dl.google.com/android/android-sdk_r22-linux.tgz
    - tar xzf android-sdk_r22-linux.tgz
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    - echo yes | android update sdk --filter platform-tools --no-ui --force
    - echo yes | android update sdk --filter build-tools-18.1.1 --no-ui --force
    - echo yes | android update sdk --filter android-18 --no-ui --force
    - echo yes | android update sdk --filter sysimg-18 --no-ui --force
    - echo yes | android update sdk --filter extra-android-support --no-ui --force
    - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force
    - wget https://raw.github.com/graingert/Dropbox-Uploader/patch-1/dropbox_uploader.sh -O dropbox_uploader.sh
script:
    - ./gradlew build
    
after_success:
    - touch dropbox_conf_empty.conf
    - bash dropbox_uploader.sh -f ./dropbox_conf_empty.conf upload Feedo/build/apk/Feedo-release-unsigned.apk FeedoNightly.apk 
    - bash dropbox_uploader.sh -f ./dropbox_conf_empty.conf share FeedoNightly.apk 
